In [174]:
import numpy as np

In [175]:
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print(A.shape)
print(B.shape)

(4, 2)
(2, 3)


La forma se devuelva como "NUMERO DE FILAS", "NUMERO DE COLUMNAS"

In [177]:
A[0]

array([1402,  191])

In [180]:
print(A[0][1])

191


In [181]:
print(A[0,1])

191


In [182]:
L = [[1402, 191], [1371, 821], [949, 1437], [147, 1448]]

In [184]:
L[0][0]

1402

In [185]:
L[0, 0]

TypeError: list indices must be integers or slices, not tuple

In [191]:
print(A[0,0])
print(A[1,0])
print(A[2,0])
print(A[3,0])

1402
1371
949
147


In [132]:
print(A)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]


In [133]:
print(A[:,0])

[1402 1371  949  147]


In [193]:
print(A[1,:])

[1371  821]


In [194]:
A[1]

array([1371,  821])

De esta forma se trabaja con los índices  **"FILA", "COLUMNA"**

### Vector "fila"

In [135]:
y = np.array([460, 232, 315, 178])

print(y)

[460 232 315 178]


### Vector "columna"

In [136]:
y = np.array([[460], [232], [315], [178]])

print(y)

[[460]
 [232]
 [315]
 [178]]


### Suma de matrices

In [138]:
A = np.array([[1, 0  ], [2, 5], [3, 1]])
B = np.array([[4, 0.5], [2, 5], [0, 1]])

print(A+B)

[[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]


### Multiplicación por un escalar

In [139]:
print(3*A)

[[ 3  0]
 [ 6 15]
 [ 9  3]]


In [140]:
print(A/4)

[[0.25 0.  ]
 [0.5  1.25]
 [0.75 0.25]]


In [141]:
A.dot?

Docstring:
a.dot(b, out=None)

Dot product of two arrays.

Refer to `numpy.dot` for full documentation.

See Also
--------
numpy.dot : equivalent function

Examples
--------
>>> a = np.eye(2)
>>> b = np.ones((2, 2)) * 2
>>> a.dot(b)
array([[2.,  2.],
       [2.,  2.]])

This array method can be conveniently chained:

>>> a.dot(b).dot(b)
array([[8.,  8.],
       [8.,  8.]])
Type:      builtin_function_or_method


### Multiplicación de matrices

In [197]:
A = np.array([1, 3])
y = np.array([1, 5])

print(A.dot(y))

16


In [198]:
np.dot(A, y)

16

In [203]:
A = np.array([[1, 3], [4, 0], [2, 1]])
y = np.array([1, 5])

print(A.dot(y))

[16  4  7]


In [200]:
np.dot(A, y)

16

In [201]:
np.matmul(A, y)

16

In [202]:
A@y

16

In [152]:
data = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
func = np.array([-40, 0.25])

print(data.dot(func))

[486.  314.  343.5 173. ]


In [153]:
A = np.array([[1, 3, 2], [4, 0, 1]])
B = np.array([[1, 3], [0, 1], [5, 2]])

print(A.dot(B))

[[11 10]
 [ 9 14]]


In [215]:
# Propiedad conmutativa de la suma
A = np.array([[1, 1], [0, 0]])
B = np.array([[0, 0], [2, 0]])
print(A+B)
print(B+A)

[[1 1]
 [2 0]]
[[1 1]
 [2 0]]


In [216]:
A = np.array([1, 1])
B = np.array([1, 3])
print(np.dot(A, B))
print(np.dot(B, A))

4
4


In [226]:

A = np.array([[1, 1], [0, 0]])
B = np.array([[0, 0], [2, 0]])
print(A.dot(B))
print(B.dot(A))

[[2 0]
 [0 0]]
[[0 0]
 [2 2]]


In [227]:
np.dot(A, B)

array([[2, 0],
       [0, 0]])

In [228]:
np.dot(B, A)

array([[0, 0],
       [2, 2]])

In [229]:
np.matmul(A, B)

array([[2, 0],
       [0, 0]])

In [230]:
np.matmul(B, A)

array([[0, 0],
       [2, 2]])

In [232]:
A@B

array([[2, 0],
       [0, 0]])

In [233]:
B@A

array([[0, 0],
       [2, 2]])

In [235]:
# Propiedad asociativa
C = np.array([[1, 2, 3], [4, 5, 6]])

print(A.dot(B.dot(C)))
print(A.dot(B).dot(C))

[[2 4 6]
 [0 0 0]]
[[2 4 6]
 [0 0 0]]


In [236]:
# Matriz identidad
I = np.identity(2)

print(A.dot(I))
print(I.dot(A))

[[1. 1.]
 [0. 0.]]
[[1. 1.]
 [0. 0.]]


In [122]:
I = np.eye(2)

print(I)

[[1. 0.]
 [0. 1.]]


In [123]:
np.identity??

Signature: np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> np.identity(3)
array([[1.,  0.,  0.],

### Inversa de una matriz

In [241]:
A = np.array([[1, 2], [3, 4]])
Ainv = np.linalg.inv(A)

print(Ainv)
print(Ainv.dot(A))
print(A.dot(Ainv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [32]:
A = np.array([[1, 1], [1, 5]])
Ainv = np.linalg.inv(A)

print(A)
print(Ainv)

[[1 1]
 [1 5]]
[[ 1.25 -0.25]
 [-0.25  0.25]]


In [242]:
def matprint(mat, fmt="g"):
    col_maxes = [max([len(("{:"+fmt+"}").format(x)) for x in col]) for col in mat.T]
    for x in mat:
        for i, y in enumerate(x):
            print(("{:"+str(col_maxes[i])+fmt+"}").format(y), end="  ")
        print("")

In [243]:
matprint(Ainv)

 -2     1  
1.5  -0.5  


### Mostrar matriz e índices con pandas

In [244]:
import pandas as pd

In [40]:
P = pd.DataFrame(Ainv)
print(P)

      0     1
0  1.25 -0.25
1 -0.25  0.25


### Transpuesta

In [246]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(np.transpose(A))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# Tiempos de ejecución

In [250]:
import timeit
import numpy as np

In [251]:
SIZE = 200
A = np.random.rand(SIZE,SIZE)
B = np.random.rand(SIZE,SIZE)

In [255]:
%%time
producto_a_mano = np.zeros((SIZE,SIZE))
for i in range(SIZE):
  for j in range(SIZE):
    for k in range(SIZE):
      producto_a_mano[i,k] += A[i,j]*B[j,k]

CPU times: user 3.53 s, sys: 0 ns, total: 3.53 s
Wall time: 3.53 s


In [259]:
%%time
producto_numpy = A.dot(B)

CPU times: user 12.1 ms, sys: 4.07 ms, total: 16.2 ms
Wall time: 4.93 ms


### Resolver sistemas de ecuaciones

In [261]:
from numpy import linalg as la

In [262]:
A = np.array([[1, 2],[1, 5]])
b = [3, 1]

In [264]:
x = la.solve(A, b)

In [265]:
x

array([ 4.33333333, -0.66666667])

In [266]:
A@x-b

array([0., 0.])

Además. linalg tiene funcionalidades para operar con matrices

In [172]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [173]:
Ainv = la.inv(A)