In [16]:
import numpy as np
from fractions import Fraction as frac

In [17]:
class bcolors:
    # ANSI escape sequences
    # Ver también el paquete colorama
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    TST = '\033[31;1m'
    X = '\033[4;95;1m'

In [18]:
A = np.random.randint(1, 6, [3,3])
b = np.random.randint(1, 6, [3,1])

In [19]:
def show_eqs(A, B):
    for a, b in zip(A, B):
        s = ''
        for i, aa in enumerate(a):
            s = s + f'{aa}*x{i+1} + '
        s = s[:-2] + f' = {b}'
        print(s)

In [20]:
show_eqs(A, b)

2*x1 + 1*x2 + 2*x3  = [3]
3*x1 + 5*x2 + 3*x3  = [2]
3*x1 + 2*x2 + 5*x3  = [5]


In [21]:
def show_eqs(A, B):
    for a, b in zip(A, B):
        s = ''
        for i, aa in enumerate(a):
            s = s + f'{aa}*x_{i+1} + '
        s = s[:-2] + f' = {b}'
        print(s)

In [22]:
show_eqs(A, b)

2*x_1 + 1*x_2 + 2*x_3  = [3]
3*x_1 + 5*x_2 + 3*x_3  = [2]
3*x_1 + 2*x_2 + 5*x_3  = [5]


In [23]:
def niceprint(matrix, ij=[None, None]):
    sp = ' '*50
    print(f'{bcolors.X}{sp}{bcolors.ENDC}\n')
    ki=0
    for irow, row in enumerate(matrix):
        pp = []
        for icol, rr in enumerate(row):
            if abs(rr)>1.e-8:
                r = frac(rr)
                if r.numerator > 1.e3 or r.denominator > 1.e3:
                    r = f'{rr:7.3f}'
                else:
                    r = str(frac(rr))
                if (ij[0]==irow) and (ij[1]==icol):
                    r = f'{bcolors.OKGREEN}{r}{bcolors.ENDC}'
            else:
                r = '0'
            pp.append(r)
        p = pp[:-1]
        p.append(f'{bcolors.WARNING}:{bcolors.ENDC}')
        p.append(f'{bcolors.TST}{pp[-1]}{bcolors.ENDC}')
        msg = "\t".join(p)           
        print(msg)
        print("\u001b[0m")  # reset
    return 0

In [27]:
def diag(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    for i in range(n):
        for j in range(n):
            if i != j:
                factor = M[j][i]/M[i][i]

                niceprint(M)
                for k in range(n+1):
                    M[j][k] = M[j][k] - factor * M[i][k]

    niceprint(M)
    x = b*0.
    for i in range(n):
        x[i] = M[i][n]/M[i][i]
    return M, x      

In [28]:
A = [[1, 2, 3],
     [2, 1, 4],
     [5, 2, 1]]
b = [4, 2, 5]

In [32]:
diag(A, b)

                                                  

1	2	3	:	4

2	1	4	:	2

5	2	1	:	5

                                                  

1	2	3	:	4

0	-3	-2	:	-6

5	2	1	:	5

                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	-8	-14	:	-15

                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	-8	-14	:	-15

                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	0	 -8.667	:	1

                                                  

1	0	0	:	  0.192

0	-3	-2	:	-6

0	0	 -8.667	:	1

                                                  

1	0	0	:	  0.192

0	-3	0	:	 -6.231

0	0	 -8.667	:	1



(array([[ 1.        ,  0.        ,  0.        ,  0.19230769],
        [ 0.        , -3.        ,  0.        , -6.23076923],
        [ 0.        ,  0.        , -8.66666667,  1.        ]]),
 array([ 0.19230769,  2.07692308, -0.11538462]))

## Veamos cómo hacer una matriz en latex:

$$
\left[\begin{array}{cc}
3& 2 \\
1& 2
\end{array}\right]
$$
 

$$
\left[\begin{array}{cc}
3& 2 \\
1& 2
\end{array}\right]
\left[\begin{array}{c}
x_0 \\
x_1
\end{array}\right]=
\left[\begin{array}{c}
5 \\
3
\end{array}\right]
$$

Modificamos la rutina:

In [57]:
def niceprint_latex(matrix, ij=[None, None]):
    sp = ' '*50
    print(f'{bcolors.X}{sp}{bcolors.ENDC}\n')
    ki=0
    for irow, row in enumerate(matrix):
        pp = []
        for icol, rr in enumerate(row):
            if abs(rr)>1.e-8:
                r = frac(rr)
                if r.numerator > 1.e3 or r.denominator > 1.e3:
                    r = f'{rr:7.3f}'
                else:
                    r = str(frac(rr))
                if (ij[0]==irow) and (ij[1]==icol):
                    r = f'{bcolors.OKGREEN}{r}{bcolors.ENDC}'
            else:
                r = '0'
            pp.append(r)
        p = pp[:-1]
        p.append(f'{bcolors.WARNING}:{bcolors.ENDC}')
        p.append(f'{bcolors.TST}{pp[-1]}{bcolors.ENDC}')
        msg = " & ".join(p) + '  \\\\'
        print(msg)
        print("\u001b[0m")  # reset
    return 0

In [58]:
def diag_latex(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    for i in range(n):
        for j in range(n):
            if i != j:
                factor = M[j][i]/M[i][i]

                niceprint_latex(M)
                for k in range(n+1):
                    M[j][k] = M[j][k] - factor * M[i][k]

    niceprint_latex(M)
    x = b*0.
    for i in range(n):
        x[i] = M[i][n]/M[i][i]
    return M, x 

In [59]:
diag_latex(A, b)

                                                  

1 & 2 & 3 & : & 4  \\

2 & 1 & 4 & : & 2  \\

5 & 2 & 1 & : & 5  \\

                                                  

1 & 2 & 3 & : & 4  \\

0 & -3 & -2 & : & -6  \\

5 & 2 & 1 & : & 5  \\

                                                  

1 & 2 & 3 & : & 4  \\

0 & -3 & -2 & : & -6  \\

0 & -8 & -14 & : & -15  \\

                                                  

1 & 0 &   1.667 & : & 0  \\

0 & -3 & -2 & : & -6  \\

0 & -8 & -14 & : & -15  \\

                                                  

1 & 0 &   1.667 & : & 0  \\

0 & -3 & -2 & : & -6  \\

0 & 0 &  -8.667 & : & 1  \\

                                                  

1 & 0 & 0 & : &   0.192  \\

0 & -3 & -2 & : & -6  \\

0 & 0 &  -8.667 & : & 1  \\

                                                  

1 & 0 & 0 & : &   0.192  \\

0 & -3 & 0 & : &  -6.231  \\

0 & 0 &  -8.667 & : & 1  \\



(array([[ 1.        ,  0.        ,  0.        ,  0.19230769],
        [ 0.        , -3.        ,  0.        , -6.23076923],
        [ 0.        ,  0.        , -8.66666667,  1.        ]]),
 array([ 0.19230769,  2.07692308, -0.11538462]))