In [4]:
import numpy as np

In [5]:
from mytools import bcolors, niceprint, operador

In [6]:
def diag(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    for i in range(n):
        for j in range(n):
            if i != j:
                factor = M[j][i]/M[i][i]

                niceprint(M); foo = input('')
                for k in range(n+1):
                    M[j][k] = M[j][k] - factor * M[i][k]

    niceprint(M); foo = input('')
    x = b*0.
    for i in range(n):
        x[i] = M[i][n]/M[i][i]
    return M, x          

In [7]:
A = [[1, 2, 3],
     [2, 1, 4],
     [5, 2, 1]]
b = [4, 2, 5]

In [8]:
diag(A, b)

                                                  

1	2	3	:	4

2	1	4	:	2

5	2	1	:	5



                                                  

1	2	3	:	4

0	-3	-2	:	-6

5	2	1	:	5



                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	-8	-14	:	-15



                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	-8	-14	:	-15



                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	0	 -8.667	:	1



                                                  

1	0	0	:	  0.192

0	-3	-2	:	-6

0	0	 -8.667	:	1



                                                  

1	0	0	:	  0.192

0	-3	0	:	 -6.231

0	0	 -8.667	:	1



(array([[ 1.        ,  0.        ,  0.        ,  0.19230769],
        [ 0.        , -3.        ,  0.        , -6.23076923],
        [ 0.        ,  0.        , -8.66666667,  1.        ]]),
 array([ 0.19230769,  2.07692308, -0.11538462]))

In [10]:
def diag_numpy(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            niceprint(M, [j,i]); foo = input('')
            print((f'\nfila {j}, columna {i}'
                   f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                   f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'
                   f' = {M[j][i]/M[i][i]}'))

            factor = M[j][i]/M[i][i]
            M[j,:] = M[j,:] - factor*M[i,:]

    niceprint(M); foo = input('')
    x = b*0.
    for i in range(n):
        x[i] = M[i][n]/M[i][i]

    M[:,:-1] = np.eye(n)
    M[:,-1] = x

    niceprint(M); foo = input('')

    return M, x   

In [11]:
diag_numpy(A, b)

                                                  

1	2	3	:	4

2	1	4	:	2

5	2	1	:	5




fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 2.0/1.0 = 2.0
                                                  

1	2	3	:	4

0	-3	-2	:	-6

5	2	1	:	5




fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 5.0/1.0 = 5.0
                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	-8	-14	:	-15




fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = -8.0/-3.0 = 2.6666666666666665
                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	0	 -8.667	:	1



                                                  

1	0	0	:	4

0	1	0	:	2

0	0	1	:	 -0.115



KeyboardInterrupt: Interrupted by user

In [14]:
def diag_numpy(A, b, verbose=False):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(n):
            if i != j:

                if verbose:
                    niceprint(M, [j,i]); foo = input('')
                    print((f'\nfila {j}, columna {i}'
                           f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                           f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'
                           f' = {M[j][i]/M[i][i]}'))

                factor = M[j][i]/M[i][i]
                M[j,:] = M[j,:] - factor*M[i,:]

        if verbose:
            niceprint(M); foo = input('')
    x = b*0.
    for i in range(n):
        x[i] = M[i][n]/M[i][i]

    return M, x  

In [15]:
diag_numpy(A, b)

(array([[ 1.        ,  0.        ,  0.        ,  0.19230769],
        [ 0.        , -3.        ,  0.        , -6.23076923],
        [ 0.        ,  0.        , -8.66666667,  1.        ]]),
 array([ 0.19230769,  2.07692308, -0.11538462]))

In [19]:
M, x = diag_numpy(A, b, True)

                                                  

1	2	3	:	4

2	1	4	:	2

5	2	1	:	5




fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 2.0/1.0 = 2.0
                                                  

1	2	3	:	4

0	-3	-2	:	-6

5	2	1	:	5




fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 5.0/1.0 = 5.0
                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	-8	-14	:	-15



                                                  

1	2	3	:	4

0	-3	-2	:	-6

0	-8	-14	:	-15




fila 0, columna 1 - Operación: E0 ← E0 - µ E1,
                    µ = E0y/E1y = 2.0/-3.0 = -0.6666666666666666
                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	-8	-14	:	-15




fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = -8.0/-3.0 = 2.6666666666666665
                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	0	 -8.667	:	1



                                                  

1	0	  1.667	:	0

0	-3	-2	:	-6

0	0	 -8.667	:	1




fila 0, columna 2 - Operación: E0 ← E0 - µ E2,
                    µ = E0z/E2z = 1.6666666666666667/-8.666666666666668 = -0.1923076923076923
                                                  

1	0	0	:	  0.192

0	-3	-2	:	-6

0	0	 -8.667	:	1




fila 1, columna 2 - Operación: E1 ← E1 - µ E2,
                    µ = E1z/E2z = -2.0/-8.666666666666668 = 0.23076923076923073
                                                  

1	0	0	:	  0.192

0	-3	0	:	 -6.231

0	0	 -8.667	:	1



In [17]:
M

array([[ 1.        ,  0.        ,  0.        ,  0.19230769],
       [ 0.        , -3.        ,  0.        , -6.23076923],
       [ 0.        ,  0.        , -8.66666667,  1.        ]])

In [18]:
A@x - b

array([8.8817842e-16, 0.0000000e+00, 8.8817842e-16])