In [1]:
import numpy as np

In [275]:
from mytools import bcolors, niceprint, operador, show_eqs

Copiamos el código para obtener una matriz triangular:

In [276]:
def triang_sup_numpy(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.column_stack((A, b))

    for i in range(n):
        for j in range(i+1,n):
            factor = M[j][i]/M[i][i]
            M[j,:] = M[j,:] - factor*M[i,:]
    return M  

In [277]:
A = np.random.randint(1, 6, [3,3])
b = np.random.randint(1, 6, [3,1])

In [278]:
triang_sup_numpy(A, b)

array([[ 1,  1,  3,  2],
       [ 0,  3,  2,  1],
       [ 0,  0, -6, -5]])

In [279]:
M = triang_sup_numpy(A, b)

In [280]:
print(M)

[[ 1  1  3  2]
 [ 0  3  2  1]
 [ 0  0 -6 -5]]


Ahora implementamos el método de sustutición inversa:

In [206]:
def back_sub_numpy(A, b):
    '''
    Implementa el método de sustitución inversa para
    resolver un sistema de ecuaciones representado por
    una matrix triangular superior
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.column_stack((A, b))

    for i in range(n):
        for j in range(n):
            factor = M[j][i]/M[i][i]
            M[j,:] = M[j,:] - factor*M[i,:]
    return M  

In [266]:
def show_eqs(A, B):
    for a, b in zip(A, B):
        s = ''
        for i, aa in enumerate(a):
            if abs(aa)>1.e-12:
                aij = f'{aa}*x{i+1} + ' 
            else:
                aij = ' '*6
            s = s + aij
        s = s[:-2] + f' = {b}'
        print(s)   

In [283]:
x = np.zeros(1)
M = [[1, -1, 2], [0, -1, 2], [0, 0, -6]]
b = [5,1,2]
print(M)
print(b)

[[1, -1, 2], [0, -1, 2], [0, 0, -6]]
[5, 1, 2]


In [284]:
show_eqs(M, b)

1*x1 + -1*x2 + 2*x3  = 5
      -1*x2 + 2*x3  = 1
            -6*x3  = 2


In [285]:
def back_sub(T, b):
    n = len(b)
    x = np.zeros(n)

    s = 0.
    for i in range(n-1, -1, -1):        
        x[i] = (b[i]-s)/T[i,i]
        j = i-1
        s = np.dot(T[j,j:], x[j:])
    return x

In [290]:
x = back_sub(np.array(M), np.array(b))

2 0.0 2 -6 -0.3333333333333333
1 -0.6666666666666666 1 -1 -1.6666666666666665
0 0.9999999999999999 5 1 4.0


In [291]:
2/(-6)

-0.3333333333333333

In [292]:
print(M)
print(b)

[[1, -1, 2], [0, -1, 2], [0, 0, -6]]
[5, 1, 2]


In [293]:
x

array([ 4.        , -1.66666667, -0.33333333])

In [294]:
M@x

array([5., 1., 2.])

In [295]:
b

[5, 1, 2]