In [1]:
import numpy as np
from fractions import Fraction as frac

In [2]:
x=frac(2,5)
y=frac(6,7)
print(x+y)

44/35


In [3]:
x.denominator

5

Generando matrices random

In [4]:
np.random.seed(3324523)

In [5]:
A = np.random.randint(1, 6, [3,3])
b = np.random.randint(1, 6, [3,1])

In [6]:
print(A)
print(b)

[[5 2 5]
 [3 1 2]
 [4 2 1]]
[[3]
 [4]
 [2]]


In [7]:
print(A@b)

[[33]
 [17]
 [22]]


In [8]:
print(np.dot(A, b))

[[33]
 [17]
 [22]]


In [9]:
print(np.matmul(A, b))

[[33]
 [17]
 [22]]


In [10]:
# Para hacer una matriz extendida:

M = np.column_stack((A, b))
print(A)
print(b)
print(M)

[[5 2 5]
 [3 1 2]
 [4 2 1]]
[[3]
 [4]
 [2]]
[[5 2 5 3]
 [3 1 2 4]
 [4 2 1 2]]


## funciones auxiliares

In [11]:
class bcolors:
    # ANSI escape sequences
    # Ver también el paquete colorama
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    TST = '\033[31;1m'
    X = '\033[4;95;1m'  

In [12]:
# ejemplo de uso:

print(f'\n\n{bcolors.OKBLUE}Un saludo colorido!{bcolors.ENDC}\n\n')



Un saludo colorido!




In [13]:
def niceprint(matrix, ij=[None, None]):
    sp = ' '*50
    print(f'{bcolors.X}{sp}{bcolors.ENDC}\n')
    ki=0
    for irow, row in enumerate(matrix):
        pp = []
        for icol, rr in enumerate(row):
            if abs(rr)>1.e-8:
                r = frac(rr)
                if r.numerator > 1.e3 or r.denominator > 1.e3:
                    r = f'{rr:7.3f}'
                else:
                    r = str(frac(rr))
                if (ij[0]==irow) and (ij[1]==icol):
                    r = f'{bcolors.OKGREEN}{r}{bcolors.ENDC}'
            else:
                r = '0'
            pp.append(r)
        p = pp[:-1]
        p.append(f'{bcolors.WARNING}:{bcolors.ENDC}')
        p.append(f'{bcolors.TST}{pp[-1]}{bcolors.ENDC}')
        msg = "\t".join(p)           
        print(msg)
        # print("\uI001b[0m")  # reset

In [14]:
# Ejemplo de uso:
print(M)
niceprint(M)
niceprint(M, [1, 1])

[[5 2 5 3]
 [3 1 2 4]
 [4 2 1 2]]
                                                  

5	2	5	:	3
3	1	2	:	4
4	2	1	:	2
                                                  

5	2	5	:	3
3	1	2	:	4
4	2	1	:	2


In [15]:
print(A)
print(b)

[[5 2 5]
 [3 1 2]
 [4 2 1]]
[[3]
 [4]
 [2]]


In [16]:
def show_eqs(A, B):
    for a, b in zip(A, B):
        s = ''
        for i, aa in enumerate(a):
            s = s + f'{aa}*x{i+1} + '
        s = s[:-2] + f' = {b}'
        print(s)

In [17]:
show_eqs(A, b)

5*x1 + 2*x2 + 5*x3  = [3]
3*x1 + 1*x2 + 2*x3  = [4]
4*x1 + 2*x2 + 1*x3  = [2]


## Eliminación de Gauss para hacer una matrix triangular

Primero probamos escribir el procedimiento:

In [18]:
def triang_sup(A, b):
    '''
    Implementa el método de eliminación de Gauss para
    hacer una matrix triangular
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            print(f'\nfila {j}, columna {i}')
            print(f'Operación: E{j} ← E{j} - µ E{i}')
            print(f'µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}')

In [19]:
A = [[1, 2, 3],
     [2, 1, 4],
     [5, 2, 1]]
b = [4, 2, 5]

In [20]:
print(A)
print(b)

[[1, 2, 3], [2, 1, 4], [5, 2, 1]]
[4, 2, 5]


In [21]:
triang_sup(A, b)


fila 1, columna 0
Operación: E1 ← E1 - µ E0
µ = E1x/E0x = 2.0/1.0

fila 2, columna 0
Operación: E2 ← E2 - µ E0
µ = E2x/E0x = 5.0/1.0

fila 2, columna 1
Operación: E2 ← E2 - µ E1
µ = E2y/E1y = 2.0/1.0


In [22]:
V = [[1,2,3,4],[5,5,6,7]]

In [23]:
V

[[1, 2, 3, 4], [5, 5, 6, 7]]

In [24]:
V = np.array(V)

In [25]:
V.shape

(2, 4)

In [26]:
np.zeros([2,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [27]:
def triang_sup(A, b):
    '''
    Implementa el método de eliminación de Gauss para
    hacer una matrix triangular
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M = np.zeros((n, n+1))
    M[:,:-1] = A
    M[:,-1] = b
    M = np.column_stack((A, b))


    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            print((f'\nfila {j}, columna {i}'
                   f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                   f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'))

In [28]:
triang_sup(A, b)


fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 2/1

fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 5/1

fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = 2/1


Ahora hacemos la cuenta:

In [31]:
def triang_sup(A, b):
    '''
    Implementa el método de eliminación de Gauss para
    hacer una matrix triangular
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            niceprint(M, [j,i]); foo = input('')
            print((f'\nfila {j}, columna {i}'
                   f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                   f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'))
            factor = M[j][i]/M[i][i]

            for k in range(n+1):
                M[j,k] = M[j,k] - factor * M[i,k]
                
    niceprint(M); foo = input('')

    return M 

In [42]:
A = [[2,4,3],[4, 8, 1],[2,2,1]]
b = [1,1,1]

In [46]:
A = [[2,4,3],[2,2,1],[4, 8, 1]]
b = [1,1,1]

In [47]:
M = triang_sup(A, b)

                                                  

2	4	3	:	1
2	2	1	:	1
4	8	1	:	1



fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 2.0/2.0
                                                  

2	4	3	:	1
0	-2	-2	:	0
4	8	1	:	1



fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 4.0/2.0
                                                  

2	4	3	:	1
0	-2	-2	:	0
0	0	-5	:	-1



fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = 0.0/-2.0
                                                  

2	4	3	:	1
0	-2	-2	:	0
0	0	-5	:	-1


In [ ]:
def triang_sup_numpy(A, b):
    '''
    Implementa el método de eliminación de Gauss para resolver
    un sistema de ecuaciones
    '''
    A = np.array(A) 
    b = np.array(b) 
    n = len(b)
    M = np.zeros((A.shape[0],A.shape[1]+1))
    M[:,:-1] = A
    M[:,-1] = b

    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            niceprint(M, [j,i]); foo = input('')
            print((f'\nfila {j}, columna {i}'
                   f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                   f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'
                   f' = {M[j][i]/M[i][i]}'))

            factor = M[j][i]/M[i][i]
            M[j,:] = M[j,:] - factor*M[i,:]

    niceprint(M); foo = input('')

    return M  

In [252]:
triang_sup_numpy(A, b)

                                                  

1	2	3	:	4
2	1	4	:	2
5	2	1	:	5



fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 2.0/1.0 = 2.0
                                                  

1	2	3	:	4
0	-3	-2	:	-6
5	2	1	:	5



fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 5.0/1.0 = 5.0
                                                  

1	2	3	:	4
0	-3	-2	:	-6
0	-8	-14	:	-15



fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = -8.0/-3.0 = 2.6666666666666665
                                                  

1	2	3	:	4
0	-3	-2	:	-6
0	0	 -8.667	:	1


KeyboardInterrupt: Interrupted by user

In [253]:
def operador(i, j, mu=None, f=None, n=3):
    """
    Construye un operador matricial para la operacion:
    F[f] ← F[i] + mu*F[j]
    """
    M = np.eye(n)
    if mu is None:
        # permutar filas
        aux = M[i,:].copy()
        M[i,:] = M[j,:]
        M[j,:] = aux
    else:
        nuevafila = M[i,:] + mu*M[j,:]
        M[f,:] = nuevafila
    return M

ejemplo de como se usa:

In [260]:
# intercambiar las filas 0 y 1
op = operador(0,1)
I = np.eye(3)
print(op)
print(I)
W = op@I
print(W)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [257]:
A = np.random.randint(1, 6, [3,3])
A = A.astype(float)
print(A, '\n\n', operador(0,1)@A)

[[4. 5. 3.]
 [5. 2. 4.]
 [3. 5. 3.]] 

 [[5. 2. 4.]
 [4. 5. 3.]
 [3. 5. 3.]]


In [261]:
# intercambiar las filas 2 y 1
operador(2,1)

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [262]:
print(A, '\n\n', operador(2,1)@A)

[[4. 5. 3.]
 [5. 2. 4.]
 [3. 5. 3.]] 

 [[4. 5. 3.]
 [3. 5. 3.]
 [5. 2. 4.]]


In [263]:
# hacer  fila1 <--- fila1 - 2.5 * fila0

operador(1, 0, 2.5, 1)

array([[1. , 0. , 0. ],
       [2.5, 1. , 0. ],
       [0. , 0. , 1. ]])

In [264]:
A = [[2,1,1],[1,5,2],[3,2,3]]
A = np.array(A).astype(float)
print(A, '\n\n', operador(1, 0, -1/2, 1)@A)

[[2. 1. 1.]
 [1. 5. 2.]
 [3. 2. 3.]] 

 [[2.  1.  1. ]
 [0.  4.5 1.5]
 [3.  2.  3. ]]


In [265]:
def triang_sup_operador(A, b):

    n = len(b)
    M = np.column_stack((np.array(A), np.array(b)))
    vname = ['x','y','z','v','w','p','q','g','s','d']

    for i in range(n):
        for j in range(i+1,n):

            print((f'\nfila {j}, columna {i}'
                   f' - Operación: E{j} ← E{j} - µ E{i},\n                   '
                   f' µ = E{j}{vname[i]}/E{i}{vname[i]} = {M[j][i]}/{M[i][i]}'))
            niceprint(M, [j,i]); foo = input('')

            op = operador(j, i, -M[j][i]/M[i][i], j, n)
            M = op@M

    niceprint(M); foo = input('')

    return M   

In [266]:
A = np.random.randint(1, 6, [3,3])
b = np.random.randint(1, 6, [3,1])

In [267]:
A

array([[4, 1, 5],
       [1, 2, 5],
       [2, 4, 4]])

In [268]:
b

array([[2],
       [3],
       [1]])

In [ ]:
triang_sup_operador(A, b)


fila 1, columna 0 - Operación: E1 ← E1 - µ E0,
                    µ = E1x/E0x = 1/4
                                                  

4	1	5	:	2
1	2	5	:	3
2	4	4	:	1



fila 2, columna 0 - Operación: E2 ← E2 - µ E0,
                    µ = E2x/E0x = 2.0/4.0
                                                  

4	1	5	:	2
0	7/4	15/4	:	5/2
2	4	4	:	1



fila 2, columna 1 - Operación: E2 ← E2 - µ E1,
                    µ = E2y/E1y = 3.5/1.75
                                                  

4	1	5	:	2
0	7/4	15/4	:	5/2
0	7/2	3/2	:	0


                                                  

4	1	5	:	2
0	7/4	15/4	:	5/2
0	0	-6	:	-5
